config/routes.rb
Byshbrowser::Application.routes.draw do

  namespace :admin do |admin|
    resources :users
  end
  
  resource :user_sessions
  # Browser matches
  match 'browsers/*path' => 'folders#show'
  match 'download/*path' => 'folders#create'

  match 'zip/*path' => 'folders#zip'  
  match 'browsers/' => 'folders#show'

  resource :folders
  resources :short_links
  
 root :to => "folders#show"
end

app/models/short_link.rb
class ShortLink < ActiveRecord::Base
  validates_presence_of :path
  validates_uniqueness_of :hash
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	 acts_as_authentic do |c|
	   c.ignore_blank_passwords = true
   end
   
   has_many :short_links

	 validates_presence_of :login, :home_folder
	 validates_confirmation_of :password_confirmation, :on => :create, :message => "should match confirmation"
	 validates_length_of :password, :minimum => 6, :on => :create
	 validates_format_of :login, :with => /^[a-zA-Z][a-zA-Z0-9]+$/, :on => :create
	 
	 def full_path
	   $PREFIX_PATH + self.home_folder
   end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < InheritedResources::Base
  before_filter :require_admin_user
  
  def create
    create! { admin_users_path }
  end
  
  def update
    update!(:notice => "Account information updated.") { accounts_path }
  end
  
  def edit
    @user = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_user
  
  private
  # file sending
  def send_wrapper(path, user = current_user)
    if Byshbrowser::Application.config.action_dispatch.x_sendfile_header.blank? 
      send_file(user.full_path + "/"+  path)
    else
      send_nginx(path, user)
    end
  end
  
  def send_nginx(path, user = current_user)
    response.headers['X-Accel-Redirect'] = "/xdownload/" + user.home_folder + "/" + path
    response.headers['Content-Type'] = 'application/octet-stream'
    response.headers['Content-Disposition'] = "attachment; filename=#{File.basename(path)}"
    render :nothing => true
  end

  # auth
  
  def require_admin_user
     unless current_user && current_user.is_admin?
       flash[:notice] = "You must be logged in to access this page"
       redirect_to new_user_sessions_path
       return false
     end
   end

   def require_user
      unless current_user
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_sessions_url
        return false
      end
   end

   def current_user_session
     return @current_user_session if defined?(@current_user_session)
     @current_user_session = UserSession.find(User.first)
   end

   def current_user
     return @current_user if defined?(@current_user)
     @current_user = current_user_session && current_user_session.user
   end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def show
    if params[:path].blank?
      @path = @current_user.full_path
    else
      @path = @current_user.full_path + "/" + params[:path]
    end
    @home_folder = @current_user.full_path
  end
  
  def create
    path = params[:path]
    send_wrapper(path)
  end
  
  def zip
    streaming = false #params[:streaming] || 0
    
    relative_path = params[:path]
    absolute_path = @current_user.full_path + "/" + relative_path
    relative_containing_folder = relative_path.gsub(File.basename(relative_path),"")
    absolute_containing_folder = absolute_path.gsub(File.basename(relative_path),"")
    
    Dir.chdir(absolute_containing_folder)

    if streaming
      # LOOK AT THIS MESS!!! WIP WIP
      # response.headers['Content-Type'] = 'application/octet-stream'
      # response.headers['Content-Disposition'] = "attachment; filename=#{File.basename(relative_path)}.zip"      
      # p = IO.popen("zip -r - \"#{absolute_path}\"","r")
      # self.response_body do 
      #    p.read
      #  end
#      while !p.eof? do 
       # send_data p.read, :filename => "#{File.basename(relative_path)}.zip", :type => 'application/zip', :disposition => 'attachment'
 #     end
      # end
      return 
      # return
      # p = IO.popen("zip -r - #{relative_path}") 
      #p.readlines
      # send_data p.read, :filename => "preview.pdf", :type => 'application/pdf', :disposition => 'inline'
      
    else
      IO.popen("zip -r \"#{absolute_path}.\"zip \"#{relative_path}\"")
      flash[:notice] = "Zipping in background, check back later."
    end
    if relative_containing_folder.blank?
      redirect_to folders_path
    else
      redirect_to url_for(:controller => "folders", :action => "show", :path => relative_containing_folder)
    end
  end

end

app/controllers/short_links_controller.rb
class ShortLinksController < InheritedResources::Base
  skip_before_filter :require_user
  
  respond_to :js

  def destroy
    @link = current_user.short_links.find(params[:id])
    @link.deleted = true
    if @link.save
      flash[:notice] = "Link deleted"
    else
      flash[:notice] = "Deletion failed"
    end
    redirect_to short_links_path
  end

  def index
    @links = current_user.short_links.where(:deleted => false)
  end

  def create
    hash = Digest::MD5.hexdigest(params[:path] + current_user.id.to_s)
    @link = ShortLink.find_or_initialize_by_hash(hash)
    @link.path = params[:path]
    @link.user_id = current_user.id    
    @link.save
  end
  
  def show
    @link = ShortLink.find_by_hash(params[:id])
    @link.counter = (@link.counter + 1)
    @link.first_hit_on = Time.now if @link.first_hit_on.blank?
    @link.save
    @home_folder = @link.path

    if @link.blank?
      render :text => "Link not found."
    end
  
    looking_for = @link.user.full_path + "/" + @link.path
    if File.exists?(looking_for)
      if File.directory?(looking_for)
        # secure browse at some point
        render :text => "Share is a folder."
      else
        send_wrapper(@link.path, @link.user)
      end
    else
      render :text => "File/Folder not found."
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  skip_before_filter :require_user, :except => :destroy

  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session].reverse_merge(:remember_me => true))
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_to folders_path
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  skip_before_filter :require_user
  def create
    create! { new_account_path }
  end
  
  def update
    update!(:notice => "Account information updated.") { accounts_path }
  end
  
  def edit
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<h1>Users</h1>
<table>
	<thead>
		<th>Login</th>
		<th>Home path</th>
		<th>Is admin?</th>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr class="<%= cycle("alt-row","")%>">		
			<td><%= user.login %></td>
			<td><%= user.full_path %></td>
			<td><%= user.is_admin? ? "Yes" : "No" %></td>			
		<tr>			
		<% end %>
	</tbody>
</table>
<p><%= link_to "Add user",  new_admin_user_path %></p>

app/views/admin/users/new.html.erb
<h1>New user</h1>
<%= semantic_form_for([:admin,@user]) do |f| %>
	<%= f.input :login %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>	
	<%= f.input :home_folder %>
	<%= f.input :is_admin?, :as => :select %>
	<%= f.submit "Create" %>
<% end %>

app/views/folders/show.html.erb
<h1>ByshBrowsing in: <%= @path %></h1>
<p><%= link_to "Manage short-links", short_links_path %></p>
<div class="files">
	<table>
		<thead>
				<th>&nbsp;</th>
				<th>Name</th>
				<th>Size</th>
				<th>Date</th>
				<th>Actions</th>
		</thead>
		<tbody>
	<% Dir.entries(@path).sort {|x,y| (File.directory?(@path + "/" +y) ? 1 : 0) <=> (File.directory?(@path + "/" +x) ? 1 : 0)}.each do |e| %>
	<%# Dir.foreach(@path) do |e| %>
	<% next if ["."].include?(e) %>
	<% next if e[0].chr == "." unless e == ".."%>
	<tr class="<%= cycle("alt-row","")%>">
		<td><% if File.directory?(@path + "/" + e) %><%= image_tag("folder.png")%><% else %><%= image_tag("document-binary.png") %><% end %></td>
		<% if File.directory?(@path + "/" + e) %>
			<td><%= link_to e, url_for(:controller => "folders", :action => "show", :path => [@path.gsub(@home_folder,""), e].join("/")) %></td>
		<% else %>
			<td><%= link_to e, url_for(:controller => "folders", :action => "create", :path => [@path.gsub(@home_folder,""), e].join("/"))%></td>

		<% end %>
		<td><%= number_to_human_size(File.size(@path + "/" + e).to_i) %></td>
		<td><%= File.ctime(@path + "/" + e) %></td>
		<td>
			<% if @link.blank? %>
				<% unless [".",".."].include?(e)%>
					<%= link_to image_tag("document-zipper.png", :alt => "Zip & Download", :title => "Zip & Download"), "#zip-#{File.stat(@path + "/" + e).ino}", :rel => "facebox" %>
					<% unless File.directory?(@path + "/" + e)%>
						<%= link_to image_tag("document-share.png", :alt => "Share file"), short_links_path(:path => @path.gsub(@home_folder,"") + "/" + e, :format => "js"), :method => :post, :remote => true %>
					<% end %>
				<% end %>
			<% end %>
		</td>
	</tr>
	<div id="zip-<%= File.stat(@path + "/" + e).ino%>" style="display:none">
		<h2>Zip options</h2>
		<p>More options will follow.</p>
		<ul>
			<li><%= link_to "Zip in background", url_for(:controller => "folders", :action => "zip", :path => [@path.gsub(@home_folder,""), e].join("/")) %></li>
		</ul>
	</div>
	<% end %>
	</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Byshbrowser</title>
  <%= stylesheet_link_tag :all %>
	<%= javascript_include_tag "jquery.min.js", "jquery.rails.js", "facebox.js" %>  
  <%= csrf_meta_tag %>
</head>
<body>
<div id="main-content">
	<% if flash[:notice].present? %>
		<div class="flash notice">
			<%= flash[:notice] %>
		</div>
	<% end %>
	<% if @current_user.present? %>
		<p>Current user: <%= @current_user.login%>, <%= link_to "logout", user_sessions_path(), :method => :delete %></p>
	<% end %>
	<%= yield %>
</div>
<script>
	jQuery(document).ready(function($) {
		$('a[rel*=facebox]').facebox()
	})
</script>
</body>
</html>

app/views/short_links/create.js.erb
jQuery.facebox('Your unique download url is:<br/> <input type="text" size=75 value="<%= short_link_url(@link.hash) %>"/>');

app/views/short_links/index.html.erb
<h1>Shortified links</h1>
<%= link_to "Back to browser", root_path %>
<table>
	<thead>
		<th>File</th>
		<th>Hash</th>
		<th>Created at</th>
		<th>Times downloaded</th>
		<th>Actions</th>
	</thead>
	<tbody>
		<% @links.each do |link| %>
			<tr class="<%= cycle("alt-row","")%>">
				<td><%= link.path %></td>
				<td><%= link.hash %></td>
				<td><%= link.created_at %></td>
				<td><%= link.counter %></td>
				<td><%= link_to "Delete", short_link_path(link), :method => :delete %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<% semantic_form_for(@user_session, :url => user_sessions_path) do |f| %>			
	<%= f.inputs do %>
		<%= f.input :login %>
		<div style="clear:both"></div>
		<%= f.input :password %>
	<% end %>
			<div style="clear:both"></div>
  <%= f.buttons do %>
     <%= f.commit_button "Login", :button_html => { :class => "button" }  %>
   <% end %>
<% end %>